#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
# MindIE is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

import time
from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, PrivateAttr

from httpx import AsyncClient

from motor.common.resources.endpoint import Endpoint
from motor.common.resources.instance import Instance, PDRole


class RequestType(Enum):
    OPENAI = "openai"
    TRITON = "triton"
    TGI = "tgi"
    VLLM = "vllm"
    MINDIE = "mindie"


class ReqState(Enum):
    ARRIVE = 'Arrive'               # Request arrive
    P_SCHEDULING = 'P_Scheduling'   # Currently scheduling P instance
    P_ALLOCATED = 'P_Allocated'     # Allocated P instance
    PREFILL_END = 'Prefill End'     # Prefill completed
    FIRST_TOKEN_FINISH = 'First Token Finish'   # First decoded token
    D_SCHEDULING = 'D_Scheduling'   # Currently scheduling D instance
    D_ALLOCATED = 'D_Allocated'     # Allocated D instance
    DECODE_END = 'Decode End'       # Decode completed
    INVALID = 'Invalid'             # Invalid state
    TIMEOUT = 'Timeout'             # Request timeout
    EXCEPTION = 'Exception'         # Request exception
    RECOMPUTE = 'Recompute'         # Recomputation


class RequestInfo(BaseModel):
    req_id: str = Field(..., description="Request ID generated by RequestManager")
    req_data: dict = Field(..., description="Request json content")
    req_len: int = Field(..., description="Request body length")
    api: str = Field(..., description="API need to be forwarded")
    state: ReqState = Field(default=ReqState.ARRIVE, description="Request current status")
    status: dict[ReqState, float] = Field(default={}, description="Request status time")
    _prefill_client: Optional[AsyncClient] = PrivateAttr(default=None)
    _decode_client: Optional[AsyncClient] = PrivateAttr(default=None)

    def __init__(self, **data):
        super().__init__(**data)
        self.status[ReqState.ARRIVE] = time.time()

    def update_state(self, new_state: ReqState):
        self.state = new_state
        self.status[new_state] = time.time()

    def set_client(self, client: AsyncClient, role: PDRole):
        if role == PDRole.ROLE_P:
            self._prefill_client = client
        if role == PDRole.ROLE_D:
            self._decode_client = client
    
    async def close_clients(self):
        if self._prefill_client and not self._prefill_client.is_closed:
            await self._prefill_client.aclose()
        if self._decode_client and not self._decode_client.is_closed:
            await self._decode_client.aclose()


class ScheduledResource(BaseModel):
    """Represents a scheduled resource with an instance and endpoint"""
    instance: Instance = None
    endpoint: Endpoint = None


class RequestResponse(BaseModel):
    request_id: str
    status: str
    message: Optional[str] = None
    data: Optional[Dict[str, Any]] = None


class ErrorResponse(BaseModel):
    message: str
    type: str
    code: int