apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mindie-pymotor-deployer
subjects:
  - kind: ServiceAccount
    name: mindie-pymotor-deployer
    namespace: mindie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mindie-pymotor-deployer
