apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mindie-pymotor-deployer
rules:
  - apiGroups: [""]
    resources: ["configmaps", "serviceaccounts"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: ["mindcluster.huawei.com"]
    resources: ["inferservicesets"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "create", "patch", "delete"]
